language: java
jdk:
- oraclejdk8
script: mvn clean package
addons:
  artifacts: true
deploy:
  provider: releases
  api_key:
    secure: KezwxspNuCLcycpau770jh9yHN5c5Lqd6ysX/qRT9S6L+ZmfygjnZAXBTY1/zpH05m//eCq4mXsAVIRk/VFotAmaeXhjZbQsWWOaXjUIONXblRPNhGTk93tWpEDndXvMoCMXCupjHLHyj4psvJpZXr/EZw3aKyO1hGbSgSfJIz3JWLOrUSVLe8AlACEUJGTCLD8OmSuEAkd+ELHaodc7rCQU5IAaO6Aq1NuJf1vefC7tmmFCYiXR6aKYzSrBXutXGMrJTiXWa2SO2dvHvVrXq0xQsiiU68+/WQd7ybl5ygv7WGPmVbO+e73FrE7w/XsEMVfAb+qlssuo2M297W5ltexT8ZNCTcp1Tm04OJxCo1wKhOD8Fb7N+dWFRXGtNcvhQTuKqiRazIDgBWhawvBn9lm8VrIn80kQFkU6zKuHGV0XtOZJQ55mvBVAKADJT8MrPCUfQPmiIZZCsJ27S0PnX5WNjVluTaaLLPjH2DmGfX7ycOJlItX6snd86MP3jqDQ0XX6ro29TtX3Y0Y2WWQ948waCVIqL096pOnUp7eg/bGJNtgReJLLRal/PZl3lbFzuaybWAu5Jp/ZqbZU9XwKOYcPb9Xx9a3h4ILkJ9eOcVYYLsJdG9zVmgu9iX5nCKUkQrnvo99mWuc/yg8j9QaWsEimKfkKIV6sIkh3LxO7AoU=
  file: target/*.jar
  skip_cleanup: true
  file_glob: true
  on:
    repo: Exorath/BCBasePlugin
